@authToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNYWNpZWtLMjAwMSIsImlhdCI6MTczNzkzMTk4NiwiZXhwIjoxNzM4MDE4Mzg2fQ.yCGHYzCWUN8Tj8bUhHxvsSl1ftH6gqR_X4CGvLzU0wYFKTmsjuKNlNF7P_yrrbES
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "firstName": "Maciej",
  "lastName": "Kwiatkowski",
  "username": "MaciekK2001",
  "email": "maciek-kwiatkowski@o2.pl",
  "password": "kozak334",
  "role": "USER"
}
####
POST http://localhost:8080/auth/login
Content-Type: application/json

{
"username": "MaciekK2001",
"password": "kozak334"
}
####
POST  http://localhost:8080/api/activities
Content-Type: application/json
Authorization: Bearer {{authToken}}


{
  "burntCalories": "500",
  "time": "360000",
  "type": "SWIM",
  "activityDate": "2025-01-18T12:34:56Z"
}

###
GET  http://localhost:8080/api/activities
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "userId": "6c84fb95-12c4-11ec-82a8-0242ac130001",
  "pageSize": "1",
  "pageNumber": "0",
  "sortOrder": "ASC",
  "sortBy": "createdAt"
}
###
GET  http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
GET  http://localhost:8080/api/users/ranking?pageSize=4&pageNumber=0&sortDirection=DESC
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
GET  http://localhost:8080/api/activities/6c84fb95-12c4-11ec-82a8-0242ac130003?pageSize=2&pageNumber=0&sortBy=createdAt
Content-Type: application/json
Authorization: Bearer {{authToken}}
