POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "firstName": "Maciej",
  "lastName": "Kwiatkowski",
  "username": "maciek-kwiatkowski@o2.pl",
  "password": "kozak334",
  "role": "USER"
}
####
POST http://localhost:8080/auth/login
Content-Type: application/json

{
"username": "maciek-kwiatkowski@o2.pl",
"password": "kozak334"
}
####
POST  http://localhost:8080/api/activities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJtYWNpZWsta3dpYXRrb3dza2lAbzIucGwiLCJpYXQiOjE3MTg0NDcxNjksImV4cCI6MTcxODUzMzU2OX0.ijzjVWTarUNF3CWuJbvgOQ9KwuvjkipFuijmi9teTtQMn-QflgxlloMxKDcoiELy


{
  "burntCalories": "455",
  "time": "360000",
  "type": "SWIM"
}

###
GET  http://localhost:8080/api/activities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJtYWNpZWsta3dpYXRrb3dza2lAbzIucGwiLCJpYXQiOjE3MTg0NDcxNjksImV4cCI6MTcxODUzMzU2OX0.ijzjVWTarUNF3CWuJbvgOQ9KwuvjkipFuijmi9teTtQMn-QflgxlloMxKDcoiELy

{
  "userId": "6c84fb95-12c4-11ec-82a8-0242ac130001",
  "pageSize": "1",
  "pageNumber": "0",
  "sortOrder": "ASC",
  "sortBy": "createdAt"
}
###
GET  http://localhost:8080/api/users/6c84fb95-12c4-11ec-82a8-0242ac130001?timePeriodOfActivities=30
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJtYWNpZWsta3dpYXRrb3dza2lAbzIucGwiLCJpYXQiOjE3MTg0NDcxNjksImV4cCI6MTcxODUzMzU2OX0.ijzjVWTarUNF3CWuJbvgOQ9KwuvjkipFuijmi9teTtQMn-QflgxlloMxKDcoiELy

###
GET  http://localhost:8080/api/users/ranking?pageSize=4&pageNumber=0&sortDirection=DESC
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJtYWNpZWsta3dpYXRrb3dza2lAbzIucGwiLCJpYXQiOjE3MTgyOTU2MzMsImV4cCI6MTcxODM4MjAzM30.1fknx9DShSVlvsHEx30HwYeJSQ3AS3HLtJ4Mi-KmxWIe7Xejd0dvqqZDtNU5W1G4
